### ISSUE TITLE
Missing changelog entry for `smarty.com` domain name change in the SDK

### ISSUE THREAD

**Issue by zorab47** [smartystreets/changelog#3]
My team hit an issue when the Ruby SDK changed domain names from `smartystreets.com` to `smarty.com`, and it wasn't documented in the Ruby SDK Changelog for [5.15.1](https://github.com/smartystreets/changelog/blob/master/sdk/ruby.md#5151---2023-10-24). Updating the Changelog would be helpful for others.

It included [these changes](https://github.com/smartystreets/smartystreets-ruby-sdk/compare/5.15.0...5.15.1), and specifically this commit: https://github.com/smartystreets/smartystreets-ruby-sdk/commit/4b3b8fac2777402cd5610a8834e2e681681bd0ca

**Comment by joliver** [comment]
Agreed that this should be in the SDK. I'm curious what the hit was. We still operate both domains.

**Comment by zorab47** [comment]
We use [VCR](https://github.com/vcr/vcr) in our test suite and the upgrade will require re-recording all of the interactions that hit the new domain.

It was a surprise when our test suite failed during a patch semantic version change (5.15.0 to 5.15.1).
